#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemQuanLyNhanSu.DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyNhanSu")]
	public partial class QuanLyNhanSu_DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();

        internal DataSet ExecuteQueryDataSet(string v, CommandType text)
        {
            throw new NotImplementedException();
        }

        #region Extensibility Method Definitions
        partial void OnCreated();
    partial void InsertChamCong(ChamCong instance);
    partial void UpdateChamCong(ChamCong instance);
    partial void DeleteChamCong(ChamCong instance);
    partial void InsertPhongBan(PhongBan instance);
    partial void UpdatePhongBan(PhongBan instance);
    partial void DeletePhongBan(PhongBan instance);
    partial void InsertCheDo(CheDo instance);
    partial void UpdateCheDo(CheDo instance);
    partial void DeleteCheDo(CheDo instance);
    partial void InsertDangNhap(DangNhap instance);
    partial void UpdateDangNhap(DangNhap instance);
    partial void DeleteDangNhap(DangNhap instance);
    partial void InsertDuAn(DuAn instance);
    partial void UpdateDuAn(DuAn instance);
    partial void DeleteDuAn(DuAn instance);
    partial void InsertLuong(Luong instance);
    partial void UpdateLuong(Luong instance);
    partial void DeleteLuong(Luong instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertPhanCongNV(PhanCongNV instance);
    partial void UpdatePhanCongNV(PhanCongNV instance);
    partial void DeletePhanCongNV(PhanCongNV instance);
    #endregion
		
		public QuanLyNhanSu_DatabaseDataContext() : 
				base(global::PhanMemQuanLyNhanSu.Properties.Settings.Default.QuanLyNhanSuConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyNhanSu_DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyNhanSu_DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyNhanSu_DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyNhanSu_DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChamCong> ChamCongs
		{
			get
			{
				return this.GetTable<ChamCong>();
			}
		}
		
		public System.Data.Linq.Table<PhongBan> PhongBans
		{
			get
			{
				return this.GetTable<PhongBan>();
			}
		}
		
		public System.Data.Linq.Table<CheDo> CheDos
		{
			get
			{
				return this.GetTable<CheDo>();
			}
		}
		
		public System.Data.Linq.Table<DangNhap> DangNhaps
		{
			get
			{
				return this.GetTable<DangNhap>();
			}
		}
		
		public System.Data.Linq.Table<DuAn> DuAns
		{
			get
			{
				return this.GetTable<DuAn>();
			}
		}
		
		public System.Data.Linq.Table<Luong> Luongs
		{
			get
			{
				return this.GetTable<Luong>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<PhanCongNV> PhanCongNVs
		{
			get
			{
				return this.GetTable<PhanCongNV>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChamCong")]
	public partial class ChamCong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _TenNV;
		
		private string _MaLuong;
		
		private System.Nullable<double> _LuongChinh;
		
		private System.Nullable<int> _SoNgayNghi;
		
		private System.Nullable<int> _SoNgayDiLam;
		
		private System.Nullable<double> _PhuCap;
		
		private System.Nullable<double> _TienThuong;
		
		private System.Nullable<double> _TienPhat;
		
		private System.Nullable<double> _TONGTIEN;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnTenNVChanging(string value);
    partial void OnTenNVChanged();
    partial void OnMaLuongChanging(string value);
    partial void OnMaLuongChanged();
    partial void OnLuongChinhChanging(System.Nullable<double> value);
    partial void OnLuongChinhChanged();
    partial void OnSoNgayNghiChanging(System.Nullable<int> value);
    partial void OnSoNgayNghiChanged();
    partial void OnSoNgayDiLamChanging(System.Nullable<int> value);
    partial void OnSoNgayDiLamChanged();
    partial void OnPhuCapChanging(System.Nullable<double> value);
    partial void OnPhuCapChanged();
    partial void OnTienThuongChanging(System.Nullable<double> value);
    partial void OnTienThuongChanged();
    partial void OnTienPhatChanging(System.Nullable<double> value);
    partial void OnTienPhatChanged();
    partial void OnTONGTIENChanging(System.Nullable<double> value);
    partial void OnTONGTIENChanged();
    #endregion
		
		public ChamCong()
		{
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNV", DbType="NVarChar(50)")]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this.OnTenNVChanging(value);
					this.SendPropertyChanging();
					this._TenNV = value;
					this.SendPropertyChanged("TenNV");
					this.OnTenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLuong", DbType="NVarChar(50)")]
		public string MaLuong
		{
			get
			{
				return this._MaLuong;
			}
			set
			{
				if ((this._MaLuong != value))
				{
					this.OnMaLuongChanging(value);
					this.SendPropertyChanging();
					this._MaLuong = value;
					this.SendPropertyChanged("MaLuong");
					this.OnMaLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuongChinh", DbType="Float")]
		public System.Nullable<double> LuongChinh
		{
			get
			{
				return this._LuongChinh;
			}
			set
			{
				if ((this._LuongChinh != value))
				{
					this.OnLuongChinhChanging(value);
					this.SendPropertyChanging();
					this._LuongChinh = value;
					this.SendPropertyChanged("LuongChinh");
					this.OnLuongChinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNgayNghi", DbType="Int")]
		public System.Nullable<int> SoNgayNghi
		{
			get
			{
				return this._SoNgayNghi;
			}
			set
			{
				if ((this._SoNgayNghi != value))
				{
					this.OnSoNgayNghiChanging(value);
					this.SendPropertyChanging();
					this._SoNgayNghi = value;
					this.SendPropertyChanged("SoNgayNghi");
					this.OnSoNgayNghiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNgayDiLam", DbType="Int")]
		public System.Nullable<int> SoNgayDiLam
		{
			get
			{
				return this._SoNgayDiLam;
			}
			set
			{
				if ((this._SoNgayDiLam != value))
				{
					this.OnSoNgayDiLamChanging(value);
					this.SendPropertyChanging();
					this._SoNgayDiLam = value;
					this.SendPropertyChanged("SoNgayDiLam");
					this.OnSoNgayDiLamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhuCap", DbType="Float")]
		public System.Nullable<double> PhuCap
		{
			get
			{
				return this._PhuCap;
			}
			set
			{
				if ((this._PhuCap != value))
				{
					this.OnPhuCapChanging(value);
					this.SendPropertyChanging();
					this._PhuCap = value;
					this.SendPropertyChanged("PhuCap");
					this.OnPhuCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienThuong", DbType="Float")]
		public System.Nullable<double> TienThuong
		{
			get
			{
				return this._TienThuong;
			}
			set
			{
				if ((this._TienThuong != value))
				{
					this.OnTienThuongChanging(value);
					this.SendPropertyChanging();
					this._TienThuong = value;
					this.SendPropertyChanged("TienThuong");
					this.OnTienThuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienPhat", DbType="Float")]
		public System.Nullable<double> TienPhat
		{
			get
			{
				return this._TienPhat;
			}
			set
			{
				if ((this._TienPhat != value))
				{
					this.OnTienPhatChanging(value);
					this.SendPropertyChanging();
					this._TienPhat = value;
					this.SendPropertyChanged("TienPhat");
					this.OnTienPhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGTIEN", DbType="Float")]
		public System.Nullable<double> TONGTIEN
		{
			get
			{
				return this._TONGTIEN;
			}
			set
			{
				if ((this._TONGTIEN != value))
				{
					this.OnTONGTIENChanging(value);
					this.SendPropertyChanging();
					this._TONGTIEN = value;
					this.SendPropertyChanged("TONGTIEN");
					this.OnTONGTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_ChamCong", Storage="_NhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.ChamCong = null;
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.ChamCong = this;
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhongBan")]
	public partial class PhongBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPB;
		
		private string _TenPB;
		
		private string _TruongPhong;
		
		private System.Nullable<System.DateTime> _NgayNhanChuc;
		
		private EntitySet<DuAn> _DuAns;
		
		private EntitySet<NhanVien> _NhanViens;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPBChanging(string value);
    partial void OnMaPBChanged();
    partial void OnTenPBChanging(string value);
    partial void OnTenPBChanged();
    partial void OnTruongPhongChanging(string value);
    partial void OnTruongPhongChanged();
    partial void OnNgayNhanChucChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayNhanChucChanged();
    #endregion
		
		public PhongBan()
		{
			this._DuAns = new EntitySet<DuAn>(new Action<DuAn>(this.attach_DuAns), new Action<DuAn>(this.detach_DuAns));
			this._NhanViens = new EntitySet<NhanVien>(new Action<NhanVien>(this.attach_NhanViens), new Action<NhanVien>(this.detach_NhanViens));
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPB", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPB
		{
			get
			{
				return this._MaPB;
			}
			set
			{
				if ((this._MaPB != value))
				{
					this.OnMaPBChanging(value);
					this.SendPropertyChanging();
					this._MaPB = value;
					this.SendPropertyChanged("MaPB");
					this.OnMaPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPB", DbType="NVarChar(50)")]
		public string TenPB
		{
			get
			{
				return this._TenPB;
			}
			set
			{
				if ((this._TenPB != value))
				{
					this.OnTenPBChanging(value);
					this.SendPropertyChanging();
					this._TenPB = value;
					this.SendPropertyChanged("TenPB");
					this.OnTenPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongPhong", DbType="NVarChar(50)")]
		public string TruongPhong
		{
			get
			{
				return this._TruongPhong;
			}
			set
			{
				if ((this._TruongPhong != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTruongPhongChanging(value);
					this.SendPropertyChanging();
					this._TruongPhong = value;
					this.SendPropertyChanged("TruongPhong");
					this.OnTruongPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhanChuc", DbType="Date")]
		public System.Nullable<System.DateTime> NgayNhanChuc
		{
			get
			{
				return this._NgayNhanChuc;
			}
			set
			{
				if ((this._NgayNhanChuc != value))
				{
					this.OnNgayNhanChucChanging(value);
					this.SendPropertyChanging();
					this._NgayNhanChuc = value;
					this.SendPropertyChanged("NgayNhanChuc");
					this.OnNgayNhanChucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongBan_DuAn", Storage="_DuAns", ThisKey="MaPB", OtherKey="Phong")]
		public EntitySet<DuAn> DuAns
		{
			get
			{
				return this._DuAns;
			}
			set
			{
				this._DuAns.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongBan_NhanVien", Storage="_NhanViens", ThisKey="MaPB", OtherKey="Phong")]
		public EntitySet<NhanVien> NhanViens
		{
			get
			{
				return this._NhanViens;
			}
			set
			{
				this._NhanViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_PhongBan", Storage="_NhanVien", ThisKey="TruongPhong", OtherKey="MaNV", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.PhongBans.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.PhongBans.Add(this);
						this._TruongPhong = value.MaNV;
					}
					else
					{
						this._TruongPhong = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DuAns(DuAn entity)
		{
			this.SendPropertyChanging();
			entity.PhongBan = this;
		}
		
		private void detach_DuAns(DuAn entity)
		{
			this.SendPropertyChanging();
			entity.PhongBan = null;
		}
		
		private void attach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.PhongBan = this;
		}
		
		private void detach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.PhongBan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CheDo")]
	public partial class CheDo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _BHXH;
		
		private System.Nullable<System.DateTime> _BHXHDate;
		
		private string _BHYT;
		
		private System.Nullable<System.DateTime> _BHYTS;
		
		private System.Nullable<System.DateTime> _BHYTE;
		
		private System.Nullable<bool> _ThaiSan;
		
		private System.Nullable<System.DateTime> _ThaiSanS;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnBHXHChanging(string value);
    partial void OnBHXHChanged();
    partial void OnBHXHDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBHXHDateChanged();
    partial void OnBHYTChanging(string value);
    partial void OnBHYTChanged();
    partial void OnBHYTSChanging(System.Nullable<System.DateTime> value);
    partial void OnBHYTSChanged();
    partial void OnBHYTEChanging(System.Nullable<System.DateTime> value);
    partial void OnBHYTEChanged();
    partial void OnThaiSanChanging(System.Nullable<bool> value);
    partial void OnThaiSanChanged();
    partial void OnThaiSanSChanging(System.Nullable<System.DateTime> value);
    partial void OnThaiSanSChanged();
    #endregion
		
		public CheDo()
		{
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BHXH", DbType="NVarChar(50)")]
		public string BHXH
		{
			get
			{
				return this._BHXH;
			}
			set
			{
				if ((this._BHXH != value))
				{
					this.OnBHXHChanging(value);
					this.SendPropertyChanging();
					this._BHXH = value;
					this.SendPropertyChanged("BHXH");
					this.OnBHXHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BHXHDate", DbType="Date")]
		public System.Nullable<System.DateTime> BHXHDate
		{
			get
			{
				return this._BHXHDate;
			}
			set
			{
				if ((this._BHXHDate != value))
				{
					this.OnBHXHDateChanging(value);
					this.SendPropertyChanging();
					this._BHXHDate = value;
					this.SendPropertyChanged("BHXHDate");
					this.OnBHXHDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BHYT", DbType="NVarChar(50)")]
		public string BHYT
		{
			get
			{
				return this._BHYT;
			}
			set
			{
				if ((this._BHYT != value))
				{
					this.OnBHYTChanging(value);
					this.SendPropertyChanging();
					this._BHYT = value;
					this.SendPropertyChanged("BHYT");
					this.OnBHYTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BHYTS", DbType="Date")]
		public System.Nullable<System.DateTime> BHYTS
		{
			get
			{
				return this._BHYTS;
			}
			set
			{
				if ((this._BHYTS != value))
				{
					this.OnBHYTSChanging(value);
					this.SendPropertyChanging();
					this._BHYTS = value;
					this.SendPropertyChanged("BHYTS");
					this.OnBHYTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BHYTE", DbType="Date")]
		public System.Nullable<System.DateTime> BHYTE
		{
			get
			{
				return this._BHYTE;
			}
			set
			{
				if ((this._BHYTE != value))
				{
					this.OnBHYTEChanging(value);
					this.SendPropertyChanging();
					this._BHYTE = value;
					this.SendPropertyChanged("BHYTE");
					this.OnBHYTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThaiSan", DbType="Bit")]
		public System.Nullable<bool> ThaiSan
		{
			get
			{
				return this._ThaiSan;
			}
			set
			{
				if ((this._ThaiSan != value))
				{
					this.OnThaiSanChanging(value);
					this.SendPropertyChanging();
					this._ThaiSan = value;
					this.SendPropertyChanged("ThaiSan");
					this.OnThaiSanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThaiSanS", DbType="Date")]
		public System.Nullable<System.DateTime> ThaiSanS
		{
			get
			{
				return this._ThaiSanS;
			}
			set
			{
				if ((this._ThaiSanS != value))
				{
					this.OnThaiSanSChanging(value);
					this.SendPropertyChanging();
					this._ThaiSanS = value;
					this.SendPropertyChanged("ThaiSanS");
					this.OnThaiSanSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_CheDo", Storage="_NhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.CheDo = null;
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.CheDo = this;
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DangNhap")]
	public partial class DangNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenTaiKhoan;
		
		private string _MatKhau;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenTaiKhoanChanging(string value);
    partial void OnTenTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    #endregion
		
		public DangNhap()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTaiKhoan", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenTaiKhoan
		{
			get
			{
				return this._TenTaiKhoan;
			}
			set
			{
				if ((this._TenTaiKhoan != value))
				{
					this.OnTenTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TenTaiKhoan = value;
					this.SendPropertyChanged("TenTaiKhoan");
					this.OnTenTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DuAn")]
	public partial class DuAn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDA;
		
		private string _TenDA;
		
		private string _DiaDiem;
		
		private string _Phong;
		
		private EntitySet<PhanCongNV> _PhanCongNVs;
		
		private EntityRef<PhongBan> _PhongBan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDAChanging(string value);
    partial void OnMaDAChanged();
    partial void OnTenDAChanging(string value);
    partial void OnTenDAChanged();
    partial void OnDiaDiemChanging(string value);
    partial void OnDiaDiemChanged();
    partial void OnPhongChanging(string value);
    partial void OnPhongChanged();
    #endregion
		
		public DuAn()
		{
			this._PhanCongNVs = new EntitySet<PhanCongNV>(new Action<PhanCongNV>(this.attach_PhanCongNVs), new Action<PhanCongNV>(this.detach_PhanCongNVs));
			this._PhongBan = default(EntityRef<PhongBan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDA", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDA
		{
			get
			{
				return this._MaDA;
			}
			set
			{
				if ((this._MaDA != value))
				{
					this.OnMaDAChanging(value);
					this.SendPropertyChanging();
					this._MaDA = value;
					this.SendPropertyChanged("MaDA");
					this.OnMaDAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDA", DbType="NVarChar(50)")]
		public string TenDA
		{
			get
			{
				return this._TenDA;
			}
			set
			{
				if ((this._TenDA != value))
				{
					this.OnTenDAChanging(value);
					this.SendPropertyChanging();
					this._TenDA = value;
					this.SendPropertyChanged("TenDA");
					this.OnTenDAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiem", DbType="NVarChar(50)")]
		public string DiaDiem
		{
			get
			{
				return this._DiaDiem;
			}
			set
			{
				if ((this._DiaDiem != value))
				{
					this.OnDiaDiemChanging(value);
					this.SendPropertyChanging();
					this._DiaDiem = value;
					this.SendPropertyChanged("DiaDiem");
					this.OnDiaDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phong", DbType="NVarChar(50)")]
		public string Phong
		{
			get
			{
				return this._Phong;
			}
			set
			{
				if ((this._Phong != value))
				{
					if (this._PhongBan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPhongChanging(value);
					this.SendPropertyChanging();
					this._Phong = value;
					this.SendPropertyChanged("Phong");
					this.OnPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DuAn_PhanCongNV", Storage="_PhanCongNVs", ThisKey="MaDA", OtherKey="MaDA")]
		public EntitySet<PhanCongNV> PhanCongNVs
		{
			get
			{
				return this._PhanCongNVs;
			}
			set
			{
				this._PhanCongNVs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongBan_DuAn", Storage="_PhongBan", ThisKey="Phong", OtherKey="MaPB", IsForeignKey=true)]
		public PhongBan PhongBan
		{
			get
			{
				return this._PhongBan.Entity;
			}
			set
			{
				PhongBan previousValue = this._PhongBan.Entity;
				if (((previousValue != value) 
							|| (this._PhongBan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhongBan.Entity = null;
						previousValue.DuAns.Remove(this);
					}
					this._PhongBan.Entity = value;
					if ((value != null))
					{
						value.DuAns.Add(this);
						this._Phong = value.MaPB;
					}
					else
					{
						this._Phong = default(string);
					}
					this.SendPropertyChanged("PhongBan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhanCongNVs(PhanCongNV entity)
		{
			this.SendPropertyChanging();
			entity.DuAn = this;
		}
		
		private void detach_PhanCongNVs(PhanCongNV entity)
		{
			this.SendPropertyChanging();
			entity.DuAn = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Luong")]
	public partial class Luong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLuong;
		
		private string _TenLuong;
		
		private System.Nullable<double> _LuongCB;
		
		private System.Nullable<double> _HeSoLuong;
		
		private EntitySet<NhanVien> _NhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLuongChanging(string value);
    partial void OnMaLuongChanged();
    partial void OnTenLuongChanging(string value);
    partial void OnTenLuongChanged();
    partial void OnLuongCBChanging(System.Nullable<double> value);
    partial void OnLuongCBChanged();
    partial void OnHeSoLuongChanging(System.Nullable<double> value);
    partial void OnHeSoLuongChanged();
    #endregion
		
		public Luong()
		{
			this._NhanViens = new EntitySet<NhanVien>(new Action<NhanVien>(this.attach_NhanViens), new Action<NhanVien>(this.detach_NhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLuong", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLuong
		{
			get
			{
				return this._MaLuong;
			}
			set
			{
				if ((this._MaLuong != value))
				{
					this.OnMaLuongChanging(value);
					this.SendPropertyChanging();
					this._MaLuong = value;
					this.SendPropertyChanged("MaLuong");
					this.OnMaLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLuong", DbType="NVarChar(50)")]
		public string TenLuong
		{
			get
			{
				return this._TenLuong;
			}
			set
			{
				if ((this._TenLuong != value))
				{
					this.OnTenLuongChanging(value);
					this.SendPropertyChanging();
					this._TenLuong = value;
					this.SendPropertyChanged("TenLuong");
					this.OnTenLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuongCB", DbType="Float")]
		public System.Nullable<double> LuongCB
		{
			get
			{
				return this._LuongCB;
			}
			set
			{
				if ((this._LuongCB != value))
				{
					this.OnLuongCBChanging(value);
					this.SendPropertyChanging();
					this._LuongCB = value;
					this.SendPropertyChanged("LuongCB");
					this.OnLuongCBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeSoLuong", DbType="Float")]
		public System.Nullable<double> HeSoLuong
		{
			get
			{
				return this._HeSoLuong;
			}
			set
			{
				if ((this._HeSoLuong != value))
				{
					this.OnHeSoLuongChanging(value);
					this.SendPropertyChanging();
					this._HeSoLuong = value;
					this.SendPropertyChanged("HeSoLuong");
					this.OnHeSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Luong_NhanVien", Storage="_NhanViens", ThisKey="MaLuong", OtherKey="Luong")]
		public EntitySet<NhanVien> NhanViens
		{
			get
			{
				return this._NhanViens;
			}
			set
			{
				this._NhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.Luong1 = this;
		}
		
		private void detach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.Luong1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _HoTenNV;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _GioiTinh;
		
		private string _DiaChi;
		
		private string _Phong;
		
		private string _CMND;
		
		private string _CongViec;
		
		private string _Luong;
		
		private string _GhiChu;
		
		private bool _LoaiNV;
		
		private EntityRef<ChamCong> _ChamCong;
		
		private EntitySet<PhongBan> _PhongBans;
		
		private EntityRef<CheDo> _CheDo;
		
		private EntitySet<PhanCongNV> _PhanCongNVs;
		
		private EntityRef<Luong> _Luong1;
		
		private EntityRef<PhongBan> _PhongBan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnHoTenNVChanging(string value);
    partial void OnHoTenNVChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnPhongChanging(string value);
    partial void OnPhongChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnCongViecChanging(string value);
    partial void OnCongViecChanged();
    partial void OnLuongChanging(string value);
    partial void OnLuongChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnLoaiNVChanging(bool value);
    partial void OnLoaiNVChanged();
    #endregion
		
		public NhanVien()
		{
			this._ChamCong = default(EntityRef<ChamCong>);
			this._PhongBans = new EntitySet<PhongBan>(new Action<PhongBan>(this.attach_PhongBans), new Action<PhongBan>(this.detach_PhongBans));
			this._CheDo = default(EntityRef<CheDo>);
			this._PhanCongNVs = new EntitySet<PhanCongNV>(new Action<PhanCongNV>(this.attach_PhanCongNVs), new Action<PhanCongNV>(this.detach_PhanCongNVs));
			this._Luong1 = default(EntityRef<Luong>);
			this._PhongBan = default(EntityRef<PhongBan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenNV", DbType="NVarChar(50)")]
		public string HoTenNV
		{
			get
			{
				return this._HoTenNV;
			}
			set
			{
				if ((this._HoTenNV != value))
				{
					this.OnHoTenNVChanging(value);
					this.SendPropertyChanging();
					this._HoTenNV = value;
					this.SendPropertyChanged("HoTenNV");
					this.OnHoTenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(50)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phong", DbType="NVarChar(50)")]
		public string Phong
		{
			get
			{
				return this._Phong;
			}
			set
			{
				if ((this._Phong != value))
				{
					if (this._PhongBan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPhongChanging(value);
					this.SendPropertyChanging();
					this._Phong = value;
					this.SendPropertyChanged("Phong");
					this.OnPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="NChar(9)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongViec", DbType="NVarChar(50)")]
		public string CongViec
		{
			get
			{
				return this._CongViec;
			}
			set
			{
				if ((this._CongViec != value))
				{
					this.OnCongViecChanging(value);
					this.SendPropertyChanging();
					this._CongViec = value;
					this.SendPropertyChanged("CongViec");
					this.OnCongViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Luong", DbType="NVarChar(50)")]
		public string Luong
		{
			get
			{
				return this._Luong;
			}
			set
			{
				if ((this._Luong != value))
				{
					if (this._Luong1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLuongChanging(value);
					this.SendPropertyChanging();
					this._Luong = value;
					this.SendPropertyChanged("Luong");
					this.OnLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(500)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiNV", DbType="Bit NOT NULL")]
		public bool LoaiNV
		{
			get
			{
				return this._LoaiNV;
			}
			set
			{
				if ((this._LoaiNV != value))
				{
					this.OnLoaiNVChanging(value);
					this.SendPropertyChanging();
					this._LoaiNV = value;
					this.SendPropertyChanged("LoaiNV");
					this.OnLoaiNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_ChamCong", Storage="_ChamCong", ThisKey="MaNV", OtherKey="MaNV", IsUnique=true, IsForeignKey=false)]
		public ChamCong ChamCong
		{
			get
			{
				return this._ChamCong.Entity;
			}
			set
			{
				ChamCong previousValue = this._ChamCong.Entity;
				if (((previousValue != value) 
							|| (this._ChamCong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChamCong.Entity = null;
						previousValue.NhanVien = null;
					}
					this._ChamCong.Entity = value;
					if ((value != null))
					{
						value.NhanVien = this;
					}
					this.SendPropertyChanged("ChamCong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_PhongBan", Storage="_PhongBans", ThisKey="MaNV", OtherKey="TruongPhong")]
		public EntitySet<PhongBan> PhongBans
		{
			get
			{
				return this._PhongBans;
			}
			set
			{
				this._PhongBans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_CheDo", Storage="_CheDo", ThisKey="MaNV", OtherKey="MaNV", IsUnique=true, IsForeignKey=false)]
		public CheDo CheDo
		{
			get
			{
				return this._CheDo.Entity;
			}
			set
			{
				CheDo previousValue = this._CheDo.Entity;
				if (((previousValue != value) 
							|| (this._CheDo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CheDo.Entity = null;
						previousValue.NhanVien = null;
					}
					this._CheDo.Entity = value;
					if ((value != null))
					{
						value.NhanVien = this;
					}
					this.SendPropertyChanged("CheDo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_PhanCongNV", Storage="_PhanCongNVs", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<PhanCongNV> PhanCongNVs
		{
			get
			{
				return this._PhanCongNVs;
			}
			set
			{
				this._PhanCongNVs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Luong_NhanVien", Storage="_Luong1", ThisKey="Luong", OtherKey="MaLuong", IsForeignKey=true)]
		public Luong Luong1
		{
			get
			{
				return this._Luong1.Entity;
			}
			set
			{
				Luong previousValue = this._Luong1.Entity;
				if (((previousValue != value) 
							|| (this._Luong1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Luong1.Entity = null;
						previousValue.NhanViens.Remove(this);
					}
					this._Luong1.Entity = value;
					if ((value != null))
					{
						value.NhanViens.Add(this);
						this._Luong = value.MaLuong;
					}
					else
					{
						this._Luong = default(string);
					}
					this.SendPropertyChanged("Luong1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongBan_NhanVien", Storage="_PhongBan", ThisKey="Phong", OtherKey="MaPB", IsForeignKey=true)]
		public PhongBan PhongBan
		{
			get
			{
				return this._PhongBan.Entity;
			}
			set
			{
				PhongBan previousValue = this._PhongBan.Entity;
				if (((previousValue != value) 
							|| (this._PhongBan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhongBan.Entity = null;
						previousValue.NhanViens.Remove(this);
					}
					this._PhongBan.Entity = value;
					if ((value != null))
					{
						value.NhanViens.Add(this);
						this._Phong = value.MaPB;
					}
					else
					{
						this._Phong = default(string);
					}
					this.SendPropertyChanged("PhongBan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhongBans(PhongBan entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_PhongBans(PhongBan entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_PhanCongNVs(PhanCongNV entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_PhanCongNVs(PhanCongNV entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhanCongNV")]
	public partial class PhanCongNV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDA;
		
		private string _MaNV;
		
		private System.Nullable<System.DateTime> _ThoiGianStart;
		
		private System.Nullable<System.DateTime> _ThoiGianEnd;
		
		private EntityRef<DuAn> _DuAn;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDAChanging(string value);
    partial void OnMaDAChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnThoiGianStartChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianStartChanged();
    partial void OnThoiGianEndChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianEndChanged();
    #endregion
		
		public PhanCongNV()
		{
			this._DuAn = default(EntityRef<DuAn>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDA", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDA
		{
			get
			{
				return this._MaDA;
			}
			set
			{
				if ((this._MaDA != value))
				{
					if (this._DuAn.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDAChanging(value);
					this.SendPropertyChanging();
					this._MaDA = value;
					this.SendPropertyChanged("MaDA");
					this.OnMaDAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianStart", DbType="Date")]
		public System.Nullable<System.DateTime> ThoiGianStart
		{
			get
			{
				return this._ThoiGianStart;
			}
			set
			{
				if ((this._ThoiGianStart != value))
				{
					this.OnThoiGianStartChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianStart = value;
					this.SendPropertyChanged("ThoiGianStart");
					this.OnThoiGianStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianEnd", DbType="Date")]
		public System.Nullable<System.DateTime> ThoiGianEnd
		{
			get
			{
				return this._ThoiGianEnd;
			}
			set
			{
				if ((this._ThoiGianEnd != value))
				{
					this.OnThoiGianEndChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianEnd = value;
					this.SendPropertyChanged("ThoiGianEnd");
					this.OnThoiGianEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DuAn_PhanCongNV", Storage="_DuAn", ThisKey="MaDA", OtherKey="MaDA", IsForeignKey=true)]
		public DuAn DuAn
		{
			get
			{
				return this._DuAn.Entity;
			}
			set
			{
				DuAn previousValue = this._DuAn.Entity;
				if (((previousValue != value) 
							|| (this._DuAn.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DuAn.Entity = null;
						previousValue.PhanCongNVs.Remove(this);
					}
					this._DuAn.Entity = value;
					if ((value != null))
					{
						value.PhanCongNVs.Add(this);
						this._MaDA = value.MaDA;
					}
					else
					{
						this._MaDA = default(string);
					}
					this.SendPropertyChanged("DuAn");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_PhanCongNV", Storage="_NhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.PhanCongNVs.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.PhanCongNVs.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
